[build]
  command = "npm run build"
  functions = "netlify/functions"  # Set correct functions directory
  publish = "dist"  # Adjust if your React app builds elsewhere

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server"
  status = 200
